In [1]:
# Import pandas for handling data
import pandas as pd

# Import regular expressions
import re

# Import string module to remove punctuation
import string

# Natural Language Processing library
import nltk

# Stopwords are common words like "the", "is", "and"
from nltk.corpus import stopwords

# Used to convert words into their base form
from nltk.stem import WordNetLemmatizer

# Split dataset into training and testing
from sklearn.model_selection import train_test_split

# Convert text into numerical features
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning algorithm
from sklearn.naive_bayes import MultinomialNB

# Evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\Admin\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Admin\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\Admin\anaconda3\Lib\site-pack

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\Admin\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Admin\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\Admin\anaconda3\Lib\site-pack

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\Admin\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Admin\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\Admin\anaconda3\Lib\site-pack

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



In [2]:
# Download stopwords
nltk.download("stopwords")

# Download WordNet for lemmatization
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...


True

In [4]:
# Read the JSON dataset
df = pd.read_json(r"C:\Users\Admin\Desktop\NLP\News_Category_Dataset_v3.json", lines=True)

# Display first 5 rows
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22


In [5]:
# Display number of rows and columns
print(df.shape)

# Display column names
print(df.columns)

(209527, 6)
Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')


In [6]:
# Keep only category, headline and short description
df = df[["category", "headline", "short_description"]]

In [7]:
# Create one text column by joining headline and description
df["text"] = df["headline"] + " " + df["short_description"]

# Keep only text and category columns
df = df[["text", "category"]]

# Display first few rows
df.head()

,text,category
0,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS
1,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS
2,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY
3,The Funniest Tweets From Parents This Week (Se...,PARENTING
4,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS


In [8]:
# Categories needed for the project
categories = [
    "POLITICS",
    "SPORTS",
    "BUSINESS",
    "TECH",
    "ENTERTAINMENT"
]

# Filter the dataset
df = df[df["category"].isin(categories)]

# Check available categories
print(df["category"].value_counts())

category
POLITICS         35602
ENTERTAINMENT    17362
BUSINESS          5992
SPORTS            5077
TECH              2104
Name: count, dtype: int64


In [9]:
# Check missing values
print(df.isnull().sum())

# Remove missing values
df.dropna(inplace=True)

text        0
category    0
dtype: int64


In [10]:
# Store English stopwords
stop_words = set(stopwords.words("english"))

# Create lemmatizer object
lemmatizer = WordNetLemmatizer()

In [11]:
# Function to clean text
def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Split sentence into words
    words = text.split()

    # Remove stopwords and apply lemmatization
    cleaned_words = []

    for word in words:
        if word not in stop_words:
            cleaned_word = lemmatizer.lemmatize(word)
            cleaned_words.append(cleaned_word)

    # Join words back into a sentence
    return " ".join(cleaned_words)

In [12]:
# Apply cleaning function to every article
df["clean_text"] = df["text"].apply(clean_text)

# Display cleaned data
df.head()

,text,category,clean_text
13,Twitch Bans Gambling Sites After Streamer Scam...,TECH,twitch ban gambling site streamer scam folk on...
17,"Maury Wills, Base-Stealing Shortstop For Dodge...",SPORTS,maury will basestealing shortstop dodger dy ma...
20,Golden Globes Returning To NBC In January Afte...,ENTERTAINMENT,golden globe returning nbc january year offair...
21,Biden Says U.S. Forces Would Defend Taiwan If ...,POLITICS,biden say u force would defend taiwan china in...
24,‘Beautiful And Sad At The Same Time’: Ukrainia...,POLITICS,‘beautiful sad time’ ukrainian cultural festiv...


In [13]:
# Create TF-IDF object
vectorizer = TfidfVectorizer(max_features=5000)

# Convert text into numerical features
X = vectorizer.fit_transform(df["clean_text"])

# Target variable
y = df["category"]

In [14]:
# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (52909, 5000)
Testing Data: (13228, 5000)


In [15]:
# Create Naive Bayes model
model = MultinomialNB()

# Train the model
model.fit(X_train, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](5,)","[ 4766.,13861.,28526., 4071., 1685.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](5,)","[-2.41,-1.34,-0.62,-2.56,-3.45]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[<U13](5,)","['BUSINESS','ENTERTAINMENT','POLITICS','SPORTS','TECH']"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](5, 5000)","[[0. ,0.82,0. ,...,1. ,2.94,2.7 ], [9.8 ,0. ,0.88,...,6.63,2.26,1.19], [4.7 ,6.66,6.55,...,3.05,7.84,8.58], [5.24,0.31,0.56,...,0. ,1.97,0. ], [0.86,0.63,0. ,...,0.76,0. ,6.41]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](5, 5000)","[[ -9.96, -9.37, -9.96,..., -9.27, -8.59, -8.66], [ -8.41,-10.78,-10.15,..., -8.75, -9.6 ,-10. ], [ -9.81, -9.51, -9.53,...,-10.15, -9.37, -9.29], [ -7.96, -9.52, -9.35,..., -9.79, -8.7 , -9.79], [ -8.65, -8.78, -9.27,..., -8.7 , -9.27, -7.27]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,5000


In [16]:
# Predict categories for testing data
y_pred = model.predict(X_test)

In [17]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8445721197459933


In [18]:
# Display precision, recall and F1-score
print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

     BUSINESS       0.78      0.47      0.58      1226
ENTERTAINMENT       0.87      0.88      0.87      3501
     POLITICS       0.83      0.97      0.90      7076
       SPORTS       0.92      0.58      0.71      1006
         TECH       0.86      0.22      0.35       419

     accuracy                           0.84     13228
    macro avg       0.85      0.62      0.68     13228
 weighted avg       0.85      0.84      0.83     13228



In [19]:
# Display confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 571   76  564    5   10]
 [  12 3066  401   22    0]
 [  49  138 6863   21    5]
 [   4  182  239  581    0]
 [  96   73  156    3   91]]


In [20]:
# Enter your own news article
news = [
    "India wins the cricket world cup after defeating Australia in the final."
]

# Clean the text
news_clean = [clean_text(news[0])]

# Convert into TF-IDF features
news_vector = vectorizer.transform(news_clean)

# Predict category
prediction = model.predict(news_vector)

print("Predicted Category:", prediction[0])

Predicted Category: SPORTS


In [21]:
#MORE EXAMPLES

In [22]:
news = [
    "Virat Kohli scores a brilliant century against England."
]

news_clean = [clean_text(news[0])]
news_vector = vectorizer.transform(news_clean)

print(model.predict(news_vector)[0])

SPORTS


In [23]:
news = [
    "Google launches a new AI-powered search engine."
]

news_clean = [clean_text(news[0])]
news_vector = vectorizer.transform(news_clean)

print(model.predict(news_vector)[0])

TECH


In [24]:
news = [
    "The government introduced a new education policy in Parliament."
]

news_clean = [clean_text(news[0])]
news_vector = vectorizer.transform(news_clean)

print(model.predict(news_vector)[0])

POLITICS
